
spring:
  application:
    name: store

  flyway:
    enabled: false

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Electronic;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345678
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    open-in-view: false
      #  properties:
    #  hibernate:
      # dialect: org.hibernate.dialect.SQLServerDialect
jasypt:
  encryptor:
    password: your-secret-key
    algorithm: PBEWithMD5AndDES
    jwt:
      secret: myVerySecureKey1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
      expiration: 86400000